name: Scheduled Retrain

on:
  schedule:
    - cron: '0 0 * * 0'  # every Sunday at midnight
  workflow_dispatch:

permissions:
  contents: read

jobs:
  retrain:
    runs-on: ubuntu-latest
    env:
      # Optional non-sensitive config
      TARGET_METRIC: "auc"
      HIGHER_IS_BETTER: "true"
      # DATA_PATH: ${{ vars.DATA_PATH }}  # define in repo "Variables" if useful

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline
        run: python -u -m src.pipeline

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: retrain-artifacts
          path: |
            artifacts/models
            artifacts/metrics
          if-no-files-found: ignore
